
const d = {
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 190,
    name: '郑家豪',
    username: 'zhengjh',
    avatar_url: 'https://www.gravatar.com/avatar/48ff1559e6c09f075e6919a6db8b9fc1?s=80&d=identicon',
    email: 'zhengjh@tsintergy.com'
  },
  project: {
    id: 4759,
    name: 'rsnjs',
    description: '直接获取仓库包作为node_module使用的脚手架',
    web_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
    avatar_url: null,
    git_ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    git_http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    namespace: 'fe-component-resource',
    visibility_level: 10,
    path_with_namespace: 'tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
    default_branch: 'main',
    ci_config_path: '',
    homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
    url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git'
  },
  object_attributes: {
    assignee_id: 178,
    author_id: 190,
    created_at: '2025-12-09 19:22:54 +0800',
    description: '',
    head_pipeline_id: null,
    id: 254940,
    iid: 6,
    last_edited_at: null,
    last_edited_by_id: null,
    merge_commit_sha: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: '0' },
    merge_status: 'preparing',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'feature/test',
    source_project_id: 4759,
    state_id: 1,
    target_branch: 'main',
    target_project_id: 4759,
    time_estimate: 0,
    title: 'docs: 文档修改',
    updated_at: '2025-12-09 19:22:54 +0800',
    updated_by_id: null,
    url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs/-/merge_requests/6',
    source: {
      id: 4759,
      name: 'rsnjs',
      description: '直接获取仓库包作为node_module使用的脚手架',
      web_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      avatar_url: null,
      git_ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      git_http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      namespace: 'fe-component-resource',
      visibility_level: 10,
      path_with_namespace: 'tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      default_branch: 'main',
      ci_config_path: '',
      homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git'
    },
    target: {
      id: 4759,
      name: 'rsnjs',
      description: '直接获取仓库包作为node_module使用的脚手架',
      web_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      avatar_url: null,
      git_ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      git_http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      namespace: 'fe-component-resource',
      visibility_level: 10,
      path_with_namespace: 'tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      default_branch: 'main',
      ci_config_path: '',
      homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git'
    },
    last_commit: {
      id: '9e469f384711d07bdf746774344181d7140edc8c',
      message: 'docs: 文档修改\n',
      title: 'docs: 文档修改',
      timestamp: '2025-12-09T19:22:19+08:00',
      url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs/-/commit/9e469f384711d07bdf746774344181d7140edc8c',
      author: [Object]
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [ 178 ],
    state: 'opened',
    action: 'open'
  },
  labels: [],
  changes: { merge_status: { previous: 'unchecked', current: 'preparing' } },
  repository: {
    name: 'rsnjs',
    url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    description: '直接获取仓库包作为node_module使用的脚手架',
    homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs'
  },
  assignees: [
    {
      id: 178,
      name: 'dongbb',
      username: 'dongbb',
      avatar_url: 'http://git.tsintergy.com:8070/uploads/-/system/user/avatar/178/avatar.png',
      email: 'dongbb@tsintergy.com'
    }
  ]
}