{
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user: {
    id: 215,
    name: '张航',
    username: 'zhanghang',
    avatar_url: 'http://git.tsintergy.com:8070/uploads/-/system/user/avatar/215/avatar.png',
    email: 'zhanghang@tsintergy.com'
  },
  project: {
    id: 4759,
    name: 'rsnjs',
    description: '直接获取仓库包作为node_module使用的脚手架',
    web_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
    avatar_url: null,
    git_ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    git_http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    namespace: 'fe-component-resource',
    visibility_level: 10,
    path_with_namespace: 'tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
    default_branch: 'main',
    ci_config_path: '',
    homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
    url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git'
  },
  object_attributes: {
    assignee_id: null,
    author_id: 190,
    created_at: '2025-12-16 18:59:46 +0800',
    description: '',
    head_pipeline_id: 123948,
    id: 256622,
    iid: 8,
    last_edited_at: null,
    last_edited_by_id: null,
    merge_commit_sha: null,
    merge_error: null,
    merge_params: { force_remove_source_branch: '0' },
    merge_status: 'can_be_merged',
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: 'feature/test',
    source_project_id: 4759,
    state_id: 2,
    target_branch: 'main-fake',
    target_project_id: 4759,
    time_estimate: 0,
    title: 'docs: 文档修改',
    updated_at: '2025-12-16 19:06:32 +0800',
    updated_by_id: null,
    url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs/-/merge_requests/8',
    source: {
      id: 4759,
      name: 'rsnjs',
      description: '直接获取仓库包作为node_module使用的脚手架',
      web_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      avatar_url: null,
      git_ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      git_http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      namespace: 'fe-component-resource',
      visibility_level: 10,
      path_with_namespace: 'tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      default_branch: 'main',
      ci_config_path: '',
      homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git'
    },
    target: {
      id: 4759,
      name: 'rsnjs',
      description: '直接获取仓库包作为node_module使用的脚手架',
      web_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      avatar_url: null,
      git_ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      git_http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      namespace: 'fe-component-resource',
      visibility_level: 10,
      path_with_namespace: 'tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      default_branch: 'main',
      ci_config_path: '',
      homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs',
      url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      ssh_url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
      http_url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git'
    },
    last_commit: {
      id: '9e469f384711d07bdf746774344181d7140edc8c',
      message: 'docs: 文档修改\n',
      title: 'docs: 文档修改',
      timestamp: '2025-12-09T19:22:19+08:00',
      url: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs/-/commit/9e469f384711d07bdf746774344181d7140edc8c',
      author: [Object]
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    assignee_ids: [],
    state: 'closed',
    action: 'close'
  },
  labels: [],
  changes: {
    state_id: { previous: 1, current: 2 },
    updated_at: {
      previous: '2025-12-16 19:04:22 +0800',
      current: '2025-12-16 19:06:32 +0800'
    }
  },
  repository: {
    name: 'rsnjs',
    url: 'git@git.tsintergy.com:tsie-component/code-component/fe-component/fe-component-resource/rsnjs.git',
    description: '直接获取仓库包作为node_module使用的脚手架',
    homepage: 'http://git.tsintergy.com:8070/tsie-component/code-component/fe-component/fe-component-resource/rsnjs'
  }
}